<?php

declare(strict_types=1);

namespace Stead\Installer;

use Stead\Exception\SafeException;

/**
 * Writes `.env` from the wizard's confirmed settings.
 *
 * The installer collects four values that cannot have safe defaults — database
 * driver/host/port/database/username/password — and the chosen
 * `APP_ENV`/`SESSION_NAME`. Only the keys mirrored in `.env.example` are
 * written; anything not listed here is ignored, so we never silently carry a
 * stale setting from a previous install forward.
 */
final class ConfigWriter
{
    private const ALLOWED_KEYS = [
        'APP_ENV',
        'APP_DEBUG',
        'DB_CONNECTION',
        'DB_HOST',
        'DB_PORT',
        'DB_DATABASE',
        'DB_USERNAME',
        'DB_PASSWORD',
        'SESSION_NAME',
        'LOGGING_LEVEL',
        'LOGGING_FILE',
    ];

    /**
     * @param array<string, scalar|null> $values
     */
    public function writeEnv(string $projectRoot, array $values): void
    {
        $path = $projectRoot . '/.env';
        $contents = $this->render($values);
        $written = @file_put_contents($path, $contents);
        if ($written === false) {
            throw new SafeException(
                sprintf('Could not write "%s". Check that the project root is writable by the web server.', $path),
                ['path' => $path],
            );
        }
        @chmod($path, 0640);
    }

    /**
     * @param array<string, scalar|null> $values
     */
    private function render(array $values): string
    {
        $lines = [
            '# Generated by the Stead web installer.',
            '# Edit with care — the installer will overwrite this file on a fresh install.',
            '',
        ];
        foreach (self::ALLOWED_KEYS as $key) {
            if (!array_key_exists($key, $values)) {
                continue;
            }
            $raw = $values[$key];
            $value = $this->format($key, $raw);
            $lines[] = sprintf('%s=%s', $key, $value);
        }
        $lines[] = '';
        return implode("\n", $lines);
    }

    private function format(string $key, mixed $value): string
    {
        $string = $value === null ? '' : (string) $value;
        if ($key === 'DB_PASSWORD' && $string !== '' && $this->needsQuoting($string)) {
            return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], $string) . '"';
        }
        if ($this->needsQuoting($string)) {
            return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], $string) . '"';
        }
        return $string;
    }

    private function needsQuoting(string $value): bool
    {
        return $value === '' || preg_match('/[\s"#\'\\\\]/', $value) === 1;
    }
}